import { MenuGUI } from "./api/api";
import { Menu } from "./api/menu";

const AttackResets: string[] = [
  "dariusnoxiantacticsonh",
  "fioraflurry",
  "garenq",
  "hecarimrapidslash",
  "jaxempowertwo",
  "jaycehypercharge",
  "leonashieldofdaybreak",
  "luciane",
  "lucianq",
  "monkeykingdoubleattack",
  "mordekaisermaceofspades",
  "nasusq",
  "nautiluspiercinggaze",
  "netherblade",
  "parley",
  "poppydevastatingblow",
  "powerfist",
  "renektonpreexecute",
  "rengarq",
  "shyvanadoubleattack",
  "sivirw",
  "takedown",
  "talonnoxiandiplomacy",
  "trundletrollsmash",
  "vaynetumble",
  "vie",
  "volibearq",
  "xenzhaocombotarget",
  "yorickspectral",
];

const NoAttacks: string[] = [
  "jarvanivcataclysmattack",
  "monkeykingdoubleattack",
  "shyvanadoubleattack",
  "shyvanadoubleattackdragon",
  "zyragraspingplantattack",
  "zyragraspingplantattack2",
  "zyragraspingplantattackfire",
  "zyragraspingplantattack2fire",
];

const Attacks: string[] = [
  "caitlynheadshotmissile",
  "frostarrow",
  "garenslash2",
  "kennenmegaproc",
  "lucianpassiveattack",
  "masteryidoublestrike",
  "quinnwenhanced",
  "renektonexecute",
  "renektonsuperexecute",
  "rengarnewpassivebuffdash",
  "trundleq",
  "xenzhaothrust",
  "viktorqbuff",
  "xenzhaothrust2",
  "xenzhaothrust3",
];
